### ISSUE TITLE
Опциональное чтение конфига

### ISSUE THREAD

**Issue by pomponchik** [yar-kik/py-app-properties#9]
Хеллоу!

По-моему, было бы круто для датаклассов сделать возможность опциональной загрузки конфига из файла уже после создания инстанса. Что-то вроде:

```python
from dataclasses import dataclass
from app_properties import properties


@properties()  # Если для таких ситуаций можно будет писать без скобок - вообще отлично.
@dataclass
class DefaultConfig:
    lol: str = 'kek'


config = DefaultConfig()
config.update(filename="my_config.yml", root="config")
```

При этом я ожидаю, что те поля, которые есть в файле конфига - заберутся оттуда, а остальные останутся из оригинального определения датакласса. Также я ожидаю, что датакласс можно будет использовать с исходным инициализатором.

**Comment by yar-kik** [comment]
Хорошо, спасибо за предложение! Я подумаю как лучше это сделать. Может добавлю параметр для ленивой инициализации конфига и метод для апдейта инстанса

**Comment by yar-kik** [comment]
В релизе 1.3.0 добавил новый параметр `lazy_init` для ленивой загрузки конфига и метод `init_props`. В README все достаточно детально описано)
